import pandas as pd

description = pd.read_csv('sample_description.csv').reset_index().to_dict("records")

barcodes =  {x['run_accession']: x['fastq_ftp'].split(';')[0] for x in description}

include: "rules/get_data.smk"
include: "rules/define_version.smk"
include: "rules/run_kallisto.smk"
include: "rules/get_counts.smk"
include: "rules/secondary_analysis.smk"
include: "rules/add_uns.smk"

localrules: add_uns_to_h5ad

rule all:
    input: "SRS4824187_with_uns.h5ad"