channels:
  - r
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - anndata=0.6.19
  - appdirs=1.4.3
  - asn1crypto=1.3.0
  - async-timeout=3.0.1
  - attrs=19.3.0
  - bcrypt=3.1.7
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - bioconductor-beachmat=2.2.0
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-dropletutils=1.6.1
  - bioconductor-edger=3.28.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicalignments=1.22.0
  - bioconductor-genomicranges=1.38.0
  - bioconductor-hdf5array=1.14.0
  - bioconductor-iranges=2.20.0
  - bioconductor-limma=3.42.0
  - bioconductor-loomexperiment=1.4.0
  - bioconductor-mast=1.12.0
  - bioconductor-rhdf5=2.30.0
  - bioconductor-rhdf5lib=1.8.0
  - bioconductor-rhtslib=1.18.0
  - bioconductor-rsamtools=2.2.0
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-singlecellexperiment=1.8.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - blosc=1.19.0
  - boto3=1.14.37
  - botocore=1.17.37
  - bustools=0.40.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cachetools=4.1.1
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cni=0.6.0
  - cni-plugins=0.8.6
  - conda=4.8.3
  - conda-package-handling=1.6.0
  - configargparse=1.2.3
  - crc32c=2.0
  - cryptography=2.8
  - curl=7.71.1
  - cycler=0.10.0
  - datrie=0.8.2
  - decorator=4.4.2
  - docutils=0.15.2
  - dropbox=10.1.1
  - entrez-direct=13.3
  - expat=2.2.9
  - fftw=3.3.8
  - filechunkio=1.8
  - fit-sne=1.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-forge=1
  - freetype=2.10.2
  - fribidi=1.0.10
  - ftputil=4.0.0
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gdk-pixbuf=2.38.2
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - ghostscript=9.22
  - giflib=5.2.1
  - gitdb=4.0.5
  - gitpython=3.1.7
  - glib=2.65.0
  - gmp=6.2.0
  - gobject-introspection=1.64.1
  - google-api-core=1.22.0
  - google-auth=1.20.0
  - google-cloud-core=1.4.1
  - google-cloud-storage=1.28.1
  - google-resumable-media=0.5.1
  - googleapis-common-protos=1.51.0
  - graphite2=1.3.13
  - graphviz=2.42.3
  - grpcio=1.31.0
  - gsl=2.6
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - icu=64.2
  - idna=2.8
  - igraph=0.7.1
  - imagemagick=7.0.10_25
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.16.0
  - jpeg=9d
  - jq=1.6
  - jsonschema=3.2.0
  - jupyter_core=4.6.3
  - kallisto=0.46.1
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libarchive=3.3.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcroco=0.6.13
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libprotobuf=3.12.4
  - librsvg=2.49.3
  - libseccomp=2.4.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - llvm-tools=9.0.1
  - llvmdev=9.0.1
  - llvmlite=0.33.0
  - louvain=0.6.1
  - lz4-c=1.9.2
  - lzo=2.10
  - make=4.3
  - markupsafe=1.1.1
  - matplotlib=3.3.0
  - matplotlib-base=3.3.0
  - mock=4.0.2
  - multidict=4.7.5
  - natsort=7.0.1
  - nbformat=5.0.7
  - ncbi-ngs-sdk=2.10.4
  - ncurses=6.2
  - networkx=2.4
  - numba=0.50.1
  - numexpr=2.7.1
  - numpy=1.19.0
  - olefile=0.46
  - oniguruma=6.9.3
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - ossuuid=1.6.2
  - pandas=1.0.5
  - pandoc=2.10
  - pango=1.42.4
  - parallel-fastq-dump=0.6.6
  - paramiko=2.7.1
  - patsy=0.5.1
  - pcre=8.44
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-base=2.23
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.36
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-html-parser=3.72
  - perl-html-tagset=3.20
  - perl-html-tree=5.07
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-io-html=1.001
  - perl-io-socket-ssl=2.066
  - perl-libwww-perl=6.39
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-mime-base64=3.15
  - perl-mozilla-ca=20180117
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-parent=0.236
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-test-requiresinternet=0.05
  - perl-time-local=1.28
  - perl-try-tiny=0.30
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-libxml=2.0132
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-xsloader=0.24
  - pillow=7.2.0
  - pip=20.1.1
  - pixman=0.38.0
  - pkg-config=0.29.2
  - prettytable=0.7.2
  - protobuf=3.12.4
  - psutil=5.7.2
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycairo=1.19.1
  - pycosat=0.6.3
  - pycparser=2.19
  - pygments=2.6.1
  - pygraphviz=1.3
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysam=0.16.0.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-igraph=0.8.2
  - python-irodsclient=0.8.2
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.1.2
  - r-abind=1.4_5
  - r-argparse=1.1.1
  - r-ape=5.4
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.8
  - r-base=3.6.3
  - r-base64enc=0.1_3
  - r-bh=1.72.0_3
  - r-bibtex=0.4.2.2
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-broom=0.7.0
  - r-callr=3.4.3
  - r-catools=1.18.0
  - r-cellranger=1.1.0
  - r-cli=2.0.2
  - r-clipr=0.7.0
  - r-cluster=2.1.0
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-cowplot=1.0.0
  - r-crayon=1.3.4
  - r-crosstalk=1.1.0.1
  - r-curl=4.3
  - r-data.table=1.12.8
  - r-dbi=1.1.0
  - r-dbplyr=1.4.4
  - r-desc=1.2.0
  - r-digest=0.6.25
  - r-dplyr=1.0.0
  - r-dqrng=0.2.1
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-fitdistrplus=1.1_1
  - r-forcats=0.5.0
  - r-formatr=1.7
  - r-fs=1.4.2
  - r-functools=0.2.0
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.18.0
  - r-future.apply=1.6.0
  - r-gbrd=0.4_11
  - r-gdata=2.18.0
  - r-generics=0.0.2
  - r-ggplot2=3.3.2
  - r-ggrepel=0.8.2
  - r-ggridges=0.5.2
  - r-globals=0.12.5
  - r-glue=1.4.1
  - r-gplots=3.0.4
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-haven=2.3.1
  - r-hexbin=1.28.1
  - r-highr=0.8
  - r-hms=0.5.3
  - r-htmltools=0.5.0
  - r-htmlwidgets=1.5.1
  - r-httr=1.4.1
  - r-ica=1.0_2
  - r-igraph=1.2.5
  - r-irlba=2.3.3=r36h7fa42b6_3
  - r-isoband=0.2.2
  - r-jsonlite=1.7.0
  - r-kernsmooth=2.23_17
  - r-knitr=1.29
  - r-labeling=0.3
  - r-lambda.r=1.2.4
  - r-later=1.1.0.1
  - r-lattice=0.20_41
  - r-lazyeval=0.2.2
  - r-lifecycle=0.2.0
  - r-listenv=0.8.0
  - r-lmtest=0.9_37
  - r-locfit=1.5_9.4
  - r-lsei=1.2_0.1
  - r-lubridate=1.7.9
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_51.6
  - r-matrix=1.2_18
  - r-matrixstats=0.56.0
  - r-metap=1.1
  - r-mgcv=1.8_31
  - r-mime=0.9
  - r-modelr=0.1.8
  - r-munsell=0.5.0
  - r-nlme=3.1_148
  - r-npsurv=0.4_0.1
  - r-openssl=1.4.2
  - r-pbapply=1.4_2
  - r-pillar=1.4.6
  - r-pkgbuild=1.1.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-plotly=4.9.2.1
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.3
  - r-progress=1.2.2
  - r-promises=1.1.1
  - r-ps=1.3.3
  - r-purrr=0.3.4
  - r-r.methodss3=1.8.0
  - r-r.oo=1.23.0
  - r-r.utils=2.9.2
  - r-r6=2.4.1
  - r-rann=2.6.1
  - r-rappdirs=0.3.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.5
  - r-rcppeigen=0.3.3.7.0
  - r-rcppprogress=0.4.2
  - r-rcurl=1.98_1.2
  - r-rdpack=1.0.0
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-reprex=0.3.0
  - r-reshape2=1.4.4
  - r-reticulate=1.16
  - r-rlang=0.4.7
  - r-rmarkdown=2.3
  - r-rocr=1.0_11
  - r-rprojroot=1.3_2
  - r-rstudioapi=0.11
  - r-rsvd=1.0.3
  - r-rtsne=0.15
  - r-rvest=0.3.5
  - r-scales=1.1.1
  - r-sceasy=0.0.5
  - r-sctransform=0.2.1
  - r-sdmtools=1.1_221.2
  - r-selectr=0.4_2
  - r-seurat=3.1.5=r36h0357c0b_1
  - r-sitmo=2.0.1
  - r-snow=0.4_3
  - r-stringi=1.4.6
  - r-stringr=1.4.0
  - r-survival=3.2_3
  - r-sys=3.3
  - r-testthat=2.3.2
  - r-tibble=3.0.3
  - r-tidyr=1.1.0
  - r-tidyselect=1.1.0
  - r-tidyverse=1.3.0
  - r-tinytex=0.24
  - r-tsne=0.1_3
  - r-utf8=1.1.4
  - r-vctrs=0.3.2
  - r-viridislite=0.3.0
  - r-whisker=0.4
  - r-withr=2.2.0
  - r-xfun=0.15
  - r-xml=3.99_0.3
  - r-xml2=1.3.2
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - r-zoo=1.8_8
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.22.0
  - rsa=4.6
  - ruamel_yaml=0.15.87
  - s3transfer=0.3.3
  - samtools=1.2
  - scanpy=1.4.4.post1
  - scikit-learn=0.23.1
  - scipy=1.2.1
  - seaborn=0.10.1
  - seaborn-base=0.10.1
  - sed=4.8
  - setuptools=49.2.0
  - singularity=3.6.1
  - six=1.15.0
  - smmap=3.0.4
  - snakemake=5.14.0
  - snakemake-minimal=5.14.0
  - sqlite=3.32.3
  - squashfs-tools=4.3
  - sra-tools=2.10.8
  - statsmodels=0.11.1
  - tbb=2020.1
  - texttable=1.6.2
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tktable=2.10
  - toposort=1.5
  - tornado=6.0.4
  - tqdm=4.48.0
  - traitlets=4.3.3
  - umap-learn=0.4.2
  - urllib3=1.25.8
  - wheel=0.34.2
  - wrapt=1.12.1
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.1.7
  - yarl=1.3.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
